definitions:
  dto.DepositRequest:
    properties:
      amount:
        type: number
      wallet_id:
        type: integer
    type: object
  dto.DepositResponse:
    properties:
      amount:
        type: number
      created_at:
        type: integer
      id:
        type: integer
      wallet_id:
        type: integer
    type: object
  dto.NewWalletRequest:
    properties:
      name:
        type: string
    type: object
  dto.TransferRequest:
    properties:
      amount:
        type: number
      wallet_from:
        type: integer
      wallet_to:
        type: integer
    type: object
  dto.TransferResponse:
    properties:
      amount:
        type: number
      created_at:
        type: integer
      id:
        type: integer
      wallet_from:
        type: integer
    type: object
  dto.WalletResponse:
    properties:
      Name:
        type: string
      balance:
        type: number
      created_at:
        type: integer
      id:
        type: integer
      updated_at:
        type: integer
    type: object
  service.Response:
    properties:
      data:
        type: object
      error:
        type: string
      error_detail:
        properties:
          code:
            description: Group error code
            example: 1.1.1
            type: string
          error_origin:
            description: Origin of error (group)
            example: invalid parameter
            type: string
          extra:
            additionalProperties:
              type: string
            description: Extra fields
            type: object
          id:
            description: Error Id in current request
            example: 1dQqPlQgJuPPJJfAd7pjmfBWMoP
            type: string
        type: object
      request_id:
        description: The X-Request-ID from request header. The request ID represented in the HTTP header X-Request-ID let you to link all the log lines which are common to a single web request.
        example: 948b9acf-36c0-452d-af21-66b362778fa3
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: Backend API Payment System
  termsOfService: http://swagger.io/terms/
  title: Payment System API
  version: "1.0"
paths:
  /api/v1/payment/deposit:
    post:
      consumes:
      - application/json
      description: Transferring money between wallets
      parameters:
      - description: Request Payload
        in: body
        name: Payload
        required: true
        schema:
          $ref: '#/definitions/dto.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success operation
          schema:
            allOf:
            - $ref: '#/definitions/service.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.TransferResponse'
              type: object
      summary: transfer money
      tags:
      - Payment System
  /api/v1/payment/wallet:
    get:
      consumes:
      - application/json
      description: get wallet by id
      parameters:
      - description: Wallet ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success operation
          schema:
            allOf:
            - $ref: '#/definitions/service.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.WalletResponse'
              type: object
      summary: Get wallet
      tags:
      - Payment System
    post:
      consumes:
      - application/json
      description: create new wallet, return last created id
      parameters:
      - description: Request Payload
        in: body
        name: Payload
        required: true
        schema:
          $ref: '#/definitions/dto.NewWalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success operation
          schema:
            allOf:
            - $ref: '#/definitions/service.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.WalletResponse'
              type: object
      summary: New wallet
      tags:
      - Payment System
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
